on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
   PERL_USE_UNSAFE_INC: 0
   AUTHOR_TESTING: 1
   AUTOMATED_TESTING: 1
   RELEASE_TESTING: 1
   PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.36'
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
          - '5.20'
          - '5.18'
          - '5.16'
          - '5.14'
          - '5.12'
          - '5.10'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - run: apt install -y libpopt-dev
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --notest --installdeps --with-configure --with-develop --verbose .
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test

  linux-debug:
    runs-on: ubuntu-latest

    container:
      image: simcop2387/perl-tester:5.036.000-main-debugging-quadmath-buster

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - run: apt update && apt install -y curl libpopt-dev
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl https://cpanmin.us | perl - --notest --installdeps --with-configure --with-develop --verbose .
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test

  mac:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - name: Set up Perl
        run: brew install cpanminus popt
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm --verbose --notest --installdeps --with-develop --with-configure .
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run tests (with coverage)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L https://cpanmin.us | perl - --notest Devel::Cover::Report::Coveralls
          `perl -MConfig -E'print $Config::Config{"sitebin"}'`/cover -test -report Coveralls -ignore_re easyxs

#  windows:
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@main
#        with:
#            submodules: recursive
#      - name: Set up Perl
#        run: |
#          choco install strawberryperl
#          #echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
#          echo 'C:\strawberry\c\bin' >> $GITHUB_PATH
#          echo 'C:\strawberry\perl\site\bin' >> $GITHUB_PATH
#          echo 'C:\strawberry\perl\bin' >> $GITHUB_PATH
#      - name: perl -V
#        run: perl -V
#      - name: Install Dependencies
#        run: curl -L https://cpanmin.us | perl - --notest --installdeps --with-develop --with-configure --verbose .
#      - name: perl Makefile.PL
#        run: perl Makefile.PL
#      - name: make
#        run: make
#      - name: Run Tests
#        run: prove -wlvmb t

  cygwin:
    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
            packages: perl_base perl-ExtUtils-MakeMaker make gcc-g++ libcrypt-devel libnsl-devel bash popt-devel
      - run: perl -V
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      - run: C:\cygwin\bin\bash.exe --login -c 'cpan App::cpanminus'
#        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      - name: Install Dependencies
        run: cd $GITHUB_WORKSPACE; cpanm --verbose --notest --installdeps --with-configure --with-develop .
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      - name: perl Makefile.PL
        run: cd $GITHUB_WORKSPACE; perl Makefile.PL
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      - name: make
        run: cd $GITHUB_WORKSPACE; make
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      - name: make test
        run: cd $GITHUB_WORKSPACE; make test
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

  qemu-alpine:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - i386
          - arm32v6
          - arm32v7
          - arm64v8
          - s390x

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - name: Get the qemu container
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Run tests on ${{ matrix.platform }}
        run: docker run --rm --interactive --mount type=bind,source=$(pwd),target=/host ${{ matrix.platform }}/alpine sh -c "apk add wget perl-app-cpanminus perl-dev make gcc libc-dev popt-dev; cd /host; perl -V; cpanm --verbose --notest --installdeps --with-configure --with-develop .; perl Makefile.PL; make -j3 -j3; PERL_DL_NONLAZY=1 prove -wlvmb t"
